version: "3"

services:
    traefik:
        image: traefik:latest
        restart: always
        ports:
            - 80:80
            - 443:443
        expose:
            - 8080
        networks:
            - web
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - $PWD/traefik.toml:/traefik.toml
            - $PWD/acme.json:/acme.json
        labels:
            - "traefik.port=8080"
            - "traefik.frontend.rule=Host:monitor.blabla.io"
            - "traefik.enable=true"
        container_name: traefik
    
    nginx:
        image: nginx:latest
        restart: always
        expose:
            - 80
        networks:
            - web
        labels:
            - "traefik.backend=nginx"
            - "traefik.docker.network=web"
            - "traefik.frontend.rule=PathPrefix:/"
            - "traefik.enable=true"
            - "traefik.port=80"

networks:
    web:
         external:
            name: web
