logLevel = "DEBUG"
defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  compress = true
  [entryPoints.https.tls]
    minVersion = "VersionTLS12"
    # tweak your ciphers pls
    cipherSuites = [
      "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305",
      "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
      "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
      "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256"
    ]

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "blabla.io"
watch = true
exposedbydefault = false

[acme]
email = "youremailhere@gmail.com"
storage = "acme.json"
entryPoint = "https"
OnHostRule = true

[[acme.domains]]
    main = "blabla.io"
    #Not necessary i think since OnHostRule = true
    #sans = ["monitor.blabla.io"]

[acme.httpChallenge]
entryPoint = "http"

[web]
address = ":8080"
[web.auth.basic]
users = ["admin:$2a$10$6wc9vncZFO8rq7yAawwGHOgDxhP0iPrZFZ8kStZzLok0KLAYfRMdW"]
